### PR TITLE
Fix: set minimum width for the calendar 300

### PR DESCRIPTION
**Pull request by roberbnd**
**What**
Add 300 as minimum value for the width in the calendar div

**Why**
`calendar.clientWidth` was returning `0`

### CODE REVIEW

**Comment by ghiscoding** [comment]
I'm not sure this is really the best way to do it, maybe an option might be better? or maybe set in CSS instead? The reason I think this is not ideal is because it's hidden in code, if it's really the only way then a constant set in the default file might be better. 

Another thing to note:
I'm about to switch back to the original [vanilla-calendar-pro](https://github.com/uvarov-frontend/vanilla-calendar-pro), I've pushed all my changes to the original project and I'm just waiting for 1 more PR I made to be released and when that happens I'll stop maintaining this fork which was only a temporary fork.

**Comment by roberbnd** [comment]
by default is 300 in .vanilla-calendar and It wasn't working
image

what is the "default file"?

**Comment by ghiscoding** [comment]
https://github.com/ghiscoding/vanilla-calendar-picker/blob/e4e3c4c441b4f84d48da542fab0c60a9698c28e0/package/src/scripts/default.ts#L19-L28

The CSS was all done by the original author, I think this PR and issue should be opened on the original project

**Comment by ghiscoding** [comment]
As of this morning with the latest release, all my PRs (about a dozen of them) were merged in released in the original project Vanilla-Calendar-Pro. For that reason, and because the original project has all features & fixes that I wanted, I will now switch back to the original library and stop supporting this fork. I saw that you did recreate this PR in the new project, so I will close this one. Thanks

**Pull request closed without merging**
